# Generated by Django 3.1.4 on 2020-12-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_sub_name', models.CharField(max_length=10, verbose_name='Subnet Name')),
                ('new_sub_value', models.IntegerField(verbose_name='Subnet Valuesss')),
            ],
            options={
                'verbose_name': 'NewExposure',
                'verbose_name_plural': 'NewExposures',
            },
        ),
        migrations.AlterField(
            model_name='addsublist',
            name='acc_subnet_name',
            field=models.CharField(max_length=10, verbose_name='Subnet Name'),
        ),
    ]
